spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogmodule
    username: postgres
    password: 1111
  jpa:
    properties:
        hbm2ddl:
          auto: create

