spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogmodule
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level: debug
server:
  port: 8080

