spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventorymodule
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level: debug